import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
  return <section>{children}</section>;
}
